import { CHAPTER_THREE_GAIDEN_MAP } from "./map.js";
import {
  CHAPTER_THREE_GAIDEN_UNITS,
  CHAPTER_THREE_GAIDEN_BOSS_ID,
  CHAPTER_THREE_GAIDEN_ENEMY_SPAWNS,
  CHAPTER_THREE_GAIDEN_PLAYER_SPAWNS,
  CHAPTER_THREE_GAIDEN_ROUND_TWO_REINFORCEMENT_SPAWNS,
  createChapterThreeGaidenHarold,
  createChapterThreeGaidenMage,
  createChapterThreeGaidenMarnie,
  createChapterThreeGaidenSwordThug,
  createChapterThreeGaidenThief,
} from "./units.js";
import {
  CHAPTER_THREE_GAIDEN_BATTLE_START_DIALOGUE,
  CHAPTER_THREE_GAIDEN_MARNIE_ENTRANCE_DIALOGUE,
  CHAPTER_THREE_GAIDEN_OPENING,
  CHAPTER_THREE_GAIDEN_POST_BATTLE_SCENE,
  CHAPTER_THREE_GAIDEN_TITLE,
} from "./events.js";
import { CHAPTER_THREE_GAIDEN_CHESTS, CHAPTER_THREE_GAIDEN_ITEMS, DIRK_ITEM } from "./items.js";

export const CHAPTER_THREE_GAIDEN_ID = "chapter3Gaiden";
export const CHAPTER_THREE_GAIDEN_DISPLAY_NAME = "Chapter 3: Gaiden";
export const CHAPTER_THREE_GAIDEN_OBJECTIVE = "Take the supplies you can before it is too late.";

export {
  CHAPTER_THREE_GAIDEN_BOSS_ID,
  CHAPTER_THREE_GAIDEN_BATTLE_START_DIALOGUE,
  CHAPTER_THREE_GAIDEN_ENEMY_SPAWNS,
  CHAPTER_THREE_GAIDEN_CHESTS,
  CHAPTER_THREE_GAIDEN_ITEMS,
  CHAPTER_THREE_GAIDEN_MAP,
  CHAPTER_THREE_GAIDEN_MARNIE_ENTRANCE_DIALOGUE,
  CHAPTER_THREE_GAIDEN_OPENING,
  CHAPTER_THREE_GAIDEN_PLAYER_SPAWNS,
  CHAPTER_THREE_GAIDEN_POST_BATTLE_SCENE,
  CHAPTER_THREE_GAIDEN_ROUND_TWO_REINFORCEMENT_SPAWNS,
  CHAPTER_THREE_GAIDEN_TITLE,
  CHAPTER_THREE_GAIDEN_UNITS,
  DIRK_ITEM,
  createChapterThreeGaidenHarold,
  createChapterThreeGaidenMage,
  createChapterThreeGaidenMarnie,
  createChapterThreeGaidenSwordThug,
  createChapterThreeGaidenThief,
};
