import { CHAPTER_ONE_UNITS } from "./chapter1.js";
import { CHAPTER_TWO_ALLY_UNITS } from "./chapter2.js";

export const CHAPTER_THREE_TITLE = { chapter: "Chapter 3", subtitle: "Tipen Whippet" };

export const CHAPTER_THREE_OPENING = [
  {
    type: "title",
    chapter: CHAPTER_THREE_TITLE.chapter,
    subtitle: CHAPTER_THREE_TITLE.subtitle,
    tag: "",
  },
  {
    type: "scene",
    sceneName: "Tipen Whippet Entrance",
    background: "chapter3TipenWhippetEntranceScene",
    lines: [
      { speaker: "Leon", portrait: "leonPortrait", text: "So this is civilisation?" },
      { speaker: "Kane", portrait: "kanePortrait", text: "Technically." },
      { speaker: "Leon", portrait: "leonPortrait", text: "That was not a ringing endorsement." },
      { speaker: "Kane", portrait: "kanePortrait", text: "It has a road, a shop, and three people who own opinions about lawn fertilizer. That is civilisation." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "It is Tipen Whippet." },
      { speaker: "Leon", portrait: "leonPortrait", text: "That sounds made up." },
      { speaker: "Kane", portrait: "kanePortrait", text: "Most places sound made up until you've been there." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Tipen Whippet sounds like a dog that went to private school." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "It is a town, Leon." },
      { speaker: "Leon", portrait: "leonPortrait", text: "I am not saying it is not. I am saying it sounds like it has a crest." },
      { speaker: "Kane", portrait: "kanePortrait", text: "It does." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Of course it does." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "A dog mauling a turnip." },
      { speaker: "Narration", portrait: null, text: "She strides off." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Wait! I can't tell if you're serious." },
    ],
  },
  {
    type: "scene",
    sceneName: "Tipen Whippet Main Road",
    background: "chapter3TipenWhippetMainRoadScene",
    lines: [
      { speaker: "Mara", portrait: "maraPortrait", text: "Isabella Roche, as I live and breathe." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Mara." },
      { speaker: "Mara", portrait: "maraPortrait", text: "Do not 'Mara' me like you were not going to sneak past." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "I was not sneaking." },
      { speaker: "Kane", portrait: "kanePortrait", text: "She was absolutely sneaking." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "I was walking with intent." },
      { speaker: "Mara", portrait: "maraPortrait", text: "And who is this?" },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Leon. Edwin's brother." },
      { speaker: "Mara", portrait: "maraPortrait", text: "Oh." },
      { speaker: "Leon", portrait: "leonPortrait", text: "That was a very loaded 'oh.'" },
      { speaker: "Mara", portrait: "maraPortrait", text: "Around here, love, most 'ohs' are loaded." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Your dress is beautiful." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Don't change the subject. Why is my brother problematic?" },
      { speaker: "Mara", portrait: "maraPortrait", text: "This old thing?" },
      { speaker: "Leon", portrait: "leonPortrait", text: "I know you can hear me." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "No. Do not do that. You know exactly what you are doing in that dress." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Fine. I give up." },
      { speaker: "Mara", portrait: "maraPortrait", text: "I bought it in a charity shop in Rye." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Then I must go to Rye sometime." },
      { speaker: "Leon", portrait: "leonPortrait", text: "I am sorry, is Izzy being charming?" },
      { speaker: "Kane", portrait: "kanePortrait", text: "Do not draw attention to it." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "I can be charming." },
      { speaker: "Kane", portrait: "kanePortrait", text: "Can you?" },
      { speaker: "Mara", portrait: "maraPortrait", text: "She has always been charming." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Thank you, Mara." },
      { speaker: "Mara", portrait: "maraPortrait", text: "You lot here for supplies?" },
      { speaker: "Kane", portrait: "kanePortrait", text: "Takeaway." },
      { speaker: "Mara", portrait: "maraPortrait", text: "Ah. Serious business. I'll let you get on." },
    ],
  },
  {
    type: "scene",
    sceneName: "Outside the Chinese Takeaway",
    background: "chapter3TakeawayExteriorScene",
    lines: [
      { speaker: "Leon", portrait: "leonPortrait", text: "This is the famous takeaway?" },
      { speaker: "Kane", portrait: "kanePortrait", text: "No one said famous." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Locally respected." },
      { speaker: "Leon", portrait: "leonPortrait", text: "That is what people say about haunted bridges." },
      { speaker: "Kane", portrait: "kanePortrait", text: "It is good food." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Do not. Kane once called a plate of burnt onion rings 'a culinary masterpiece.'" },
      { speaker: "Kane", portrait: "kanePortrait", text: "And it was." },
    ],
  },
  {
    type: "scene",
    sceneName: "Inside the Takeaway",
    background: "chapter3TakeawayInteriorScene",
    lines: [
      { speaker: "Gus", portrait: "gusPortrait", text: "Evening. Usual?" },
      { speaker: "Kane", portrait: "kanePortrait", text: "Usual, cheers Gus." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Add tofu." },
      { speaker: "Kane", portrait: "kanePortrait", text: "Why?" },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Because Grimmy likes it." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Grimmy likes tofu?" },
      { speaker: "Kane", portrait: "kanePortrait", text: "Grimmy likes anything he can describe as 'a texture adventure.'" },
      { speaker: "Leon", portrait: "leonPortrait", text: "Do you ever think prawns are the goblins of the sea?" },
      { speaker: "Kane", portrait: "kanePortrait", text: "No." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Absolutely not." },
      { speaker: "Leon", portrait: "leonPortrait", text: "That was too quick." },
      { speaker: "Kane", portrait: "kanePortrait", text: "It deserved speed." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Small. Suspicious. Too many legs. Feels like they know riddles." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Prawns do not know riddles." },
      { speaker: "Leon", portrait: "leonPortrait", text: "You do not know that." },
      { speaker: "Kane", portrait: "kanePortrait", text: "I know enough." },
      { speaker: "Leon", portrait: "leonPortrait", text: "If a prawn stopped me at a bridge, I would hear it out." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Why is there a bridge in the sea?" },
      { speaker: "Leon", portrait: "leonPortrait", text: "It is metaphorical." },
      { speaker: "Kane", portrait: "kanePortrait", text: "It is not." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Fine. A pier." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "That did not help." },
      { speaker: "Leon", portrait: "leonPortrait", text: "A prawn at the end of a pier asks you one question-" },
      { speaker: "Kane", portrait: "kanePortrait", text: "I am already walking away." },
      { speaker: "Leon", portrait: "leonPortrait", text: "-and if you get it wrong, you become a crab." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Why a crab?" },
      { speaker: "Leon", portrait: "leonPortrait", text: "Because crabs look like they failed a test." },
      { speaker: "Kane", portrait: "kanePortrait", text: "That might be the worst sentence I have heard today." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Today is still young." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "It is evening." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Then I have achieved something." },
      { speaker: "Kane", portrait: "kanePortrait", text: "You have achieved concern." },
      { speaker: "Leon", portrait: "leonPortrait", text: "I will take it." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Do not." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Do you think crabs know they are walking sideways, or is everyone else sideways to them?" },
      { speaker: "Kane", portrait: "kanePortrait", text: "No more animals." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Shellfish are not animals?" },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "They are." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Then I withdraw the questi-" },
      { speaker: "SFX", portrait: null, text: "A woman screams outside." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Mara." },
      { speaker: "Kane", portrait: "kanePortrait", text: "Move." },
    ],
  },
  {
    type: "scene",
    sceneName: "Mara Threatened",
    background: "chapter3MaraThreatenedScene",
    lines: [
      { type: "fullScreenScene", scene: "chapter3MaraThreatenedScene", speaker: "Mercenary", text: "Where are the Bards?" },
      { speaker: "Mara", portrait: "maraPortrait", text: "I don't know who you mean." },
      { speaker: "Mercenary", portrait: "mercenaryPortrait", text: "Wrong answer." },
      { speaker: "Mara", portrait: "maraPortrait", text: "I do not know!" },
      { speaker: "Mercenary", portrait: "mercenaryPortrait", text: "They come here. People have seen them." },
      { speaker: "Mara", portrait: "maraPortrait", text: "People see all sorts." },
      { speaker: "Mercenary", portrait: "mercenaryPortrait", text: "Not helpful." },
      { speaker: "Mara", portrait: "maraPortrait", text: "I was not trying to be." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Take your hand off her." },
      { speaker: "Mercenary", portrait: "mercenaryPortrait", text: "And there they are." },
      { type: "fullScreenScene", scene: "chapter3IzzyWindAttackScene", speaker: "SFX", text: "WHOOMPH! Izzy blasts the thug back with a burst of wind." },
      { speaker: "Leon", portrait: "leonPortrait", text: "I'm a FAN of how you work..." },
      { speaker: "Kane", portrait: "kanePortrait", text: "No." },
      { speaker: "Leon", portrait: "leonPortrait", text: "But-" },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "No." },
    ],
  },
  {
    type: "scene",
    sceneName: "Mara Afterward",
    background: "chapter3MaraAfterwardScene",
    lines: [
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Mara. Look at me. Are you hurt?" },
      { speaker: "Mara", portrait: "maraPortrait", text: "No. I am alright." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Are you sure?" },
      { speaker: "Mara", portrait: "maraPortrait", text: "I am sure." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Good." },
      { speaker: "Mara", portrait: "maraPortrait", text: "Izzy what did yo-" },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Later. Get inside and safe." },
    ],
  },
];

export const CHAPTER_THREE_POST_BATTLE_SCENE = [
  { type: "savePrompt", title: "Chapter 3 Complete", text: "Save game?" },
];

export const CHAPTER_THREE_ESCAPE_TILE = { x: 6, y: 0 };

export const CHAPTER_THREE_MAP = [
  ["street", "street", "cover", "street", "street", "street", "gate", "street"],
  ["street", "wall", "wall", "street", "cover", "street", "street", "street"],
  ["street", "street", "street", "street", "street", "cover", "street", "street"],
  ["street", "cover", "street", "street", "street", "street", "wall", "street"],
  ["street", "street", "street", "cover", "street", "street", "street", "street"],
  ["street", "street", "cover", "street", "street", "street", "cover", "street"],
  ["street", "street", "street", "street", "street", "street", "street", "street"],
  ["street", "street", "street", "street", "street", "street", "street", "street"],
];

function cloneUnit(unit, placement) {
  return {
    ...unit,
    ...placement,
    acted: false,
    spriteState: "idle",
    weapons: (unit.weapons || []).map((weapon) => ({ ...weapon })),
    skills: (unit.skills || []).map((skill) => ({ ...skill })),
    items: (unit.items || []).map((item) => ({ ...item })),
  };
}

const leon = CHAPTER_ONE_UNITS.find((unit) => unit.id === "leon");
const izzy = CHAPTER_TWO_ALLY_UNITS.find((unit) => unit.id === "izzy");
const kane = CHAPTER_TWO_ALLY_UNITS.find((unit) => unit.id === "kane");

export const CHAPTER_THREE_UNITS = [
  cloneUnit(leon, { x: 2, y: 6, facing: "up" }),
  cloneUnit(izzy, { x: 3, y: 6, facing: "up" }),
  cloneUnit(kane, { x: 4, y: 6, facing: "up" }),
  {
    id: "chapter3_mercenary",
    name: "Mercenary",
    title: "Guildlite Scout",
    team: "enemy",
    className: "Mercenary",
    portraitKey: "mercenaryPortrait",
    spriteSet: "sword_thug",
    facing: "down",
    x: 4,
    y: 2,
    move: 4,
    hp: 18,
    maxHp: 18,
    str: 6,
    mag: 0,
    def: 3,
    res: 2,
    spd: 5,
    luck: 3,
    weapons: [{ name: "Blade", baseDamage: 4, range: 1, damageType: "physical", stat: "str", hitRate: 95 }],
    skills: [],
    acted: false,
    color: 0xf87171,
  },
].filter(Boolean);
