export const ALLIED_DEATH_LINES = {
  leon: "I can't...not yet...I only just found you.",
  edwin: "Please...take care of Leon for me.",
};
export const CHAPTER_ONE_GAME_OVER_UNIT_IDS = ["edwin", "leon"];
export const CHAPTER_ONE_ESCAPE_TILE = { x: 6, y: 0 };

export const CHAPTER_ONE_MAP = [
  ["street", "cover", "street", "street", "street", "street", "gate", "street"],
  ["street", "street", "cover", "street", "street", "cover", "street", "street"],
  ["street", "wall", "wall", "street", "street", "street", "street", "street"],
  ["street", "street", "street", "cover", "street", "street", "street", "street"],
  ["street", "street", "cover", "street", "street", "wall", "wall", "street"],
  ["street", "street", "street", "street", "cover", "street", "street", "street"],
  ["street", "cover", "street", "street", "street", "street", "street", "street"],
  ["street", "street", "street", "street", "street", "street", "street", "street"],
];

export const CHAPTER_ONE_OPENING = [
  {
    type: "title",
    chapter: "Chapter 1",
    subtitle: "4 Years Gone",
    tag: "",
  },
  {
    type: "scene",
    sceneName: "Leon's House",
    background: "leonsHouseScene",
    lines: [
      { speaker: "Leon", portrait: "leonPortrait", text: "They left already...?" },
      { speaker: "Letter", portrait: null, text: "Leon, happy birthday. There's been a sighting of Edwin near Poole." },
      { speaker: "Letter", portrait: null, text: "We'll be back probably this weekend. Love, Mum and Dad." },
      { speaker: "Leon", portrait: "leonPortrait", text: "...Still looking for him." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Four years, and they still won't stop. Not even today." },
    ],
  },
  {
    type: "scene",
    sceneName: "Walk to School",
    background: "walkToSchoolScene",
    lines: [
      { speaker: "Kayley", portrait: "kayleyPortrait", text: "There he is. Birthday boy finally decided to show up." },
      { speaker: "Rich", portrait: "richPortrait", text: "You're late enough that we were about to eat your presents ourselves." },
      { speaker: "Leon", portrait: "leonPortrait", text: "You didn't get me presents." },
      { speaker: "Kayley", portrait: "kayleyPortrait", text: "Exactly. We saved money." },
      { speaker: "Rich", portrait: "richPortrait", text: "Come on. If we cut through the underpass, we'll still make it." },
    ],
  },
  {
    type: "scene",
    sceneName: "Underpass",
    background: "underpassScene",
    lines: [
      { speaker: "Rich", portrait: "richPortrait", text: "...Leon." },
      { speaker: "Kayley", portrait: "kayleyPortrait", text: "Those aren't students." },
      { speaker: "Falan", portrait: "falanPortrait", text: "There you are." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Who are you people?" },
      { speaker: "Falan", portrait: "falanPortrait", text: "Doesn't matter. You're coming with us." },
      { speaker: "Kayley", portrait: "kayleyPortrait", text: "No chance. Back off." },
      { speaker: "Rich", portrait: "richPortrait", text: "Leon, get behind us." },
      {
        type: "impact",
        attacker: "Thug",
        attackerPortrait: "thugPortrait",
        defender: "Rich",
        defenderPortrait: "richPortrait",
        text: "A thug lunges. Rich falls first.",
      },
      {
        type: "impact",
        attacker: "Thug",
        attackerPortrait: "thugPortrait",
        defender: "Kayley",
        defenderPortrait: "kayleyPortrait",
        text: "Kayley tries to pull Leon away, but another attacker cuts her down.",
      },
      { speaker: "Leon", portrait: "leonPortrait", text: "Kayley! Rich! No-!" },
      {
        type: "impact",
        attacker: "Edwin",
        attackerPortrait: "edwinPortrait",
        defender: "Thug",
        defenderPortrait: "thugPortrait",
        text: "A blue-white flash cuts across the underpass. Edwin strikes one attacker down.",
      },
      { speaker: "Edwin", portrait: "edwinPortrait", text: "Talk later. If you want answers, survive." },
      { speaker: "Leon", portrait: "leonPortrait", text: "...Edwin?" },
      { speaker: "Falan", portrait: "falanPortrait", text: "So the ghost brother finally crawls home." },
      { speaker: "Edwin", portrait: "edwinPortrait", text: "Stay behind me, Leon." },
    ],
  },
];

export const POST_BATTLE_SCENE = [
  { type: "mapDialogue", speaker: "Leon", portrait: "leonPortrait", text: "I..." },
  {
    type: "mapAction",
    speaker: "Narration",
    portrait: "edwinPortrait",
    text: "Leon passes out. Edwin rushes in and catches him before he hits the ground.",
  },
  { type: "mapDialogue", speaker: "Edwin", portrait: "edwinPortrait", text: "Woah there. I got you. Sleep for now." },
  { type: "sceneDialogue", sceneName: "Panel Van", scene: "vanInteriorScene", speaker: "Heath", portrait: "heathPortrait", text: "Hey there sleeping beauty!" },
  { type: "sceneDialogue", sceneName: "Panel Van", scene: "vanInteriorScene", speaker: "Leon", portrait: "leonPortrait", text: "Where... Where's Edwin?" },
  {
    type: "sceneDialogue",
    sceneName: "Panel Van",
    scene: "vanInteriorScene",
    speaker: "Heath",
    portrait: "heathPortrait",
    text: "The boss man is driving this heap. Name's Heath by the way, and this bundle of cuteness wrapped up is Izzy.",
  },
  { type: "sceneDialogue", sceneName: "Panel Van", scene: "vanInteriorScene", speaker: "Izzy", portrait: "izzyPortrait", text: "*Grunt*" },
  { type: "sceneDialogue", sceneName: "Panel Van", scene: "vanInteriorScene", speaker: "Leon", portrait: "leonPortrait", text: "Kayley? Rich?" },
  {
    type: "sceneDialogue",
    sceneName: "Panel Van",
    scene: "vanInteriorScene",
    speaker: "Izzy",
    portrait: "izzyPortrait",
    text: "The two you were with? Dead, I'm afraid... Any consolation, it was quick.",
  },
  { type: "sceneDialogue", sceneName: "Panel Van", scene: "vanInteriorScene", speaker: "Leon", portrait: "leonPortrait", text: "..." },
  { type: "sceneDialogue", sceneName: "Panel Van", scene: "vanInteriorScene", speaker: "Heath", portrait: "heathPortrait", text: "It's OK." },
  {
    type: "sceneNarration",
    sceneName: "Panel Van",
    scene: "vanInteriorScene",
    speaker: "Narration",
    portrait: null,
    text: "Heath pulls Leon into a hug as Leon sobs against him.",
  },
  {
    type: "overlapDialogue",
    sceneName: "Panel Van",
    scene: "vanInteriorScene",
    speaker: "Heath",
    portrait: "heathPortrait",
    overlapPortrait: "leonPortrait",
    text: "Let it all out. We'll be home soon.",
  },
  { type: "fullScreenScene", sceneName: "Byron Farm", scene: "byronFarmScene", text: "Byron Farm" },
  { type: "savePrompt", title: "Chapter 1 Complete", text: "Save game?" },
];

export const CHAPTER_ONE_UNITS = [
  {
    id: "edwin",
    name: "Edwin",
    title: "Iceblade",
    level: 5,
    xp: 0,
    xpRate: 0.65,
    sigilPoints: 3,
    maxSigilPoints: 3,
    team: "player",
    className: "Spellsword",
    portraitKey: "edwinPortrait",
    spriteSet: "edwin",
    facing: "down",
    x: 2,
    y: 6,
    move: 5,
    hp: 24,
    maxHp: 24,
    str: 8,
    mag: 10,
    def: 6,
    res: 7,
    spd: 8,
    luck: 4,
    weapons: [
      { name: "Iceblade", baseDamage: 4, range: 1, damageType: "physical", stat: "str", hitRate: 100 },
      { name: "Ice Sigil", baseDamage: 5, range: 2, damageType: "magical", stat: "mag", hitRate: 100 },
    ],
    skills: [{ id: "iceOfAges", name: "Ice of Ages", cost: 2, type: "adjacentSquare", damageFormula: "mag", animationState: "magic" }],
    acted: false,
    color: 0x60a5fa,
  },
  {
    id: "leon",
    name: "Leon",
    title: "Brawler",
    level: 1,
    xp: 0,
    xpRate: 1.5,
    sigilPoints: 3,
    maxSigilPoints: 3,
    team: "player",
    className: "Street Brawler",
    portraitKey: "leonPortrait",
    spriteSet: "leon",
    facing: "down",
    x: 4,
    y: 6,
    move: 5,
    hp: 16,
    maxHp: 16,
    str: 3,
    mag: 0,
    def: 2,
    res: 1,
    spd: 7,
    luck: 5,
    weapons: [{ name: "Fists", baseDamage: 1, range: 1, damageType: "physical", stat: "str", hitRate: 100 }],
    items: [
      {
        id: "greggsSausageRoll",
        name: "Gregg's Sausage Roll",
        heal: 10,
        uses: 1,
        targetType: "selfOrAdjacentAlly",
        description: "Restore 10 HP to Leon or an adjacent ally.",
      },
    ],
    acted: false,
    color: 0x38bdf8,
  },
  {
    id: "falan",
    name: "Falan",
    title: "Gang Leader",
    sigilPoints: 3,
    maxSigilPoints: 3,
    team: "enemy",
    className: "Leader",
    portraitKey: "falanPortrait",
    spriteSet: "falan",
    facing: "down",
    x: 4,
    y: 1,
    move: 4,
    hp: 14,
    maxHp: 14,
    str: 5,
    mag: 0,
    def: 3,
    res: 1,
    spd: 5,
    luck: 3,
    weapons: [{ name: "Katars", baseDamage: 3, range: 1, damageType: "physical", stat: "str", hitRate: 100, speedBonus: 2 }],
    deathLine: "I... didn\'t believe... Caleb... you\'re good, Bligh... but the others will end you.",
    skills: [{ id: "manicDervish", name: "Manic Dervish", cost: 3, type: "adjacentSquare", damageFormula: "strPlusSpd", animationState: "spin" }],
    acted: false,
    color: 0xf87171,
    boss: true,
  },
  {
    id: "thug1",
    name: "Thug",
    title: "White Hood",
    team: "enemy",
    className: "Thug",
    sigilPoints: 3,
    maxSigilPoints: 3,
    portraitKey: "thugPortrait",
    spriteSet: "sword_thug",
    facing: "down",
    x: 2,
    y: 1,
    move: 4,
    hp: 8,
    maxHp: 8,
    str: 3,
    mag: 0,
    def: 1,
    res: 0,
    spd: 4,
    luck: 1,
    weapons: [{ name: "Sword", baseDamage: 3, range: 1, damageType: "physical", stat: "str", hitRate: 100 }],
    acted: false,
    color: 0xfb7185,
  },
  {
    id: "thug2",
    name: "Thug",
    title: "White Hood",
    team: "enemy",
    className: "Thug",
    sigilPoints: 3,
    maxSigilPoints: 3,
    portraitKey: "thugPortrait",
    spriteSet: "axe_thug",
    facing: "down",
    x: 3,
    y: 0,
    move: 4,
    hp: 8,
    maxHp: 8,
    str: 3,
    mag: 0,
    def: 1,
    res: 0,
    spd: 4,
    luck: 0,
    weapons: [{ name: "Axe", baseDamage: 5, range: 1, damageType: "physical", stat: "str", hitRate: 75 }],
    acted: false,
    color: 0xfb7185,
  },
  {
    id: "thug3",
    name: "Thug",
    title: "White Hood",
    team: "enemy",
    className: "Thug",
    sigilPoints: 3,
    maxSigilPoints: 3,
    portraitKey: "thugPortrait",
    spriteSet: "chakram_thug",
    facing: "down",
    x: 5,
    y: 0,
    move: 4,
    hp: 8,
    maxHp: 8,
    str: 3,
    mag: 0,
    def: 1,
    res: 0,
    spd: 4,
    luck: 2,
    weapons: [{ name: "Chakram", baseDamage: 2, minRange: 1, maxRange: 2, damageType: "physical", stat: "str", hitRate: 100 }],
    acted: false,
    color: 0xfb7185,
  },
  {
    id: "thug4",
    name: "Thug",
    title: "White Hood",
    team: "enemy",
    className: "Thug",
    sigilPoints: 3,
    maxSigilPoints: 3,
    portraitKey: "thugPortrait",
    spriteSet: "sword_thug",
    facing: "down",
    x: 6,
    y: 1,
    move: 4,
    hp: 8,
    maxHp: 8,
    str: 3,
    mag: 0,
    def: 1,
    res: 0,
    spd: 4,
    luck: 1,
    weapons: [{ name: "Sword", baseDamage: 3, range: 1, damageType: "physical", stat: "str", hitRate: 100 }],
    acted: false,
    color: 0xfb7185,
  },
];
