export const CHAPTER_FOUR_NUMBER = 4;
export const CHAPTER_FOUR_TITLE = { chapter: "Chapter 4", subtitle: "Home Gone" };
export const CHAPTER_FOUR_PLAYER_SPAWNS = [
  { x: 2, y: 7, facing: "up" },
  { x: 3, y: 7, facing: "up" },
  { x: 4, y: 7, facing: "up" },
  { x: 5, y: 7, facing: "up" },
  { x: 1, y: 6, facing: "up" },
  { x: 6, y: 6, facing: "up" },
  { x: 2, y: 6, facing: "up" },
  { x: 5, y: 6, facing: "up" },
];

export const CHAPTER_FOUR_OPENING = [
  {
    type: "title",
    chapter: CHAPTER_FOUR_TITLE.chapter,
    subtitle: CHAPTER_FOUR_TITLE.subtitle,
    tag: "",
  },
  {
    type: "scene",
    sceneName: "Road Back to Byron Farm",
    background: "chapter4VanArrivalScene",
    lines: [
      { speaker: "Leon", portrait: "leonPortrait", text: "If Edwin says 'nearly there' again, I am walking into a hedge on principle." },
      { speaker: "Heath", portrait: "heathPortrait", text: "He did say nearly, not emotionally prepared." },
      { speaker: "Kane", portrait: "kanePortrait", text: "That is because no one has ever been emotionally prepared for Edwin's driving." },
      { speaker: "Edwin", portrait: "edwinPortrait", text: "I can hear you." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Good. Brake earlier." },
      { speaker: "Grimmy", portrait: "grimmyPortrait", text: "Does anyone smell smoke?" },
    ],
  },
  {
    type: "scene",
    sceneName: "Byron Farm Burning",
    background: "chapter4BurningFarmScene",
    lines: [
      { type: "fullScreenScene", scene: "chapter4BurningFarmScene", speaker: "Narration", text: "Byron Farm burns against the night." },
      { speaker: "Leon", portrait: "leonPortrait", text: "No. No, no, no." },
      { speaker: "Edwin", portrait: "edwinPortrait", text: "Everyone out. Now." },
      { speaker: "Kane", portrait: "kanePortrait", text: "Training yard's gone." },
      { speaker: "Heath", portrait: "heathPortrait", text: "The house..." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Movement by the courtyard." },
    ],
  },
  {
    type: "scene",
    sceneName: "The Guildlite Commanders",
    background: "chapter4FirelineScene",
    lines: [
      { speaker: "Bertram", portrait: "mercenaryPortrait", text: "Contact confirmed. Edwin Bligh, alive and returned to base. Years late, but still obliging enough to stand in the open." },
      { speaker: "Elspeth", portrait: "mercenaryFemalePortrait", text: "He always did come back to ruined things. It made him feel necessary." },
      { speaker: "Edwin", portrait: "edwinPortrait", text: "Bertram. Elspeth." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Friends of yours?" },
      { speaker: "Bertram", portrait: "mercenaryPortrait", text: "Commanders. Instructors. The people who remember what he was before he started playing shepherd." },
      { speaker: "Elspeth", portrait: "mercenaryFemalePortrait", text: "Little Heath. Little Kane. You were smaller at the orphanage. Louder, too, when the tests began." },
      { speaker: "Kane", portrait: "kanePortrait", text: "Say another word about that place." },
      { speaker: "Elspeth", portrait: "mercenaryFemalePortrait", text: "There it is. Still reactive. Caleb was right to doubt the conditioning." },
      { speaker: "Heath", portrait: "heathPortrait", text: "You trained children to break." },
      { speaker: "Bertram", portrait: "mercenaryPortrait", text: "We trained weapons. Some held an edge. Some snapped. Edwin here ran before we could find out which he was." },
      { speaker: "Edwin", portrait: "edwinPortrait", text: "I left because I knew what you were." },
      { speaker: "Bertram", portrait: "mercenaryPortrait", text: "No. You left because you were weak." },
      { speaker: "Elspeth", portrait: "mercenaryFemalePortrait", text: "And sentimental. Look at this farm. All that guilt, given walls." },
      { speaker: "Bertram", portrait: "mercenaryPortrait", text: "Form up, Bards. Let's see if the strays bite, or if we have to put them down in the ash." },
    ],
  },
];

export const CHAPTER_FOUR_POST_BATTLE_SCENE = [
  {
    type: "sceneDialogue",
    sceneName: "Byron Farm Embers",
    scene: "chapter4BattleCourtyardScene",
    speaker: "Leon",
    portrait: "leonPortrait",
    text: "We came home and found a battlefield.",
  },
  {
    type: "sceneDialogue",
    sceneName: "Byron Farm Embers",
    scene: "chapter4BattleCourtyardScene",
    speaker: "Edwin",
    portrait: "edwinPortrait",
    text: "Then we make sure it is still home when the smoke clears.",
  },
  { type: "savePrompt", title: "Chapter 4 Complete", text: "Save game?" },
];

export const CHAPTER_FOUR_MAP = [
  ["brokenFence", "smokeTile", "burnedGrass", "farmhouseBurned", "farmhouseBurned", "smokeTile", "scorchedGrass", "burningFence", "collapsedFence", "burnedGrass"],
  ["burnedGrass", "scorchedGrass", "burningGrass", "smokeTile", "farmhouseBurned", "burningGrass", "mudPath", "burnedGrass", "burningFence", "smokeTile"],
  ["collapsedFence", "smokeTile", "mudPath", "scorchedGrass", "burningGrass", "farmRoad", "mudPath", "smokeTile", "scorchedGrass", "brokenFence"],
  ["scorchedGrass", "mudPath", "farmRoad", "burnedGrass", "mudPath", "scorchedGrass", "farmRoad", "farmRoad", "burningGrass", "burnedGrass"],
  ["burningGrass", "brokenFence", "scorchedGrass", "smokeTile", "farmRoad", "burnedGrass", "smokeTile", "mudPath", "collapsedFence", "scorchedGrass"],
  ["burnedGrass", "mudPath", "scorchedGrass", "burningGrass", "farmRoad", "farmRoad", "mudPath", "scorchedGrass", "burningFence", "smokeTile"],
  ["smokeTile", "mudPath", "farmRoad", "scorchedGrass", "burnedGrass", "scorchedGrass", "farmRoad", "mudPath", "burnedGrass", "collapsedFence"],
  ["burnedGrass", "scorchedGrass", "farmRoad", "mudPath", "farmRoad", "mudPath", "farmRoad", "scorchedGrass", "burnedGrass", "smokeTile"],
];

export const CHAPTER_FOUR_UNITS = [
  {
    id: "bertram",
    name: "Bertram",
    title: "Guildlite Commander",
    level: 7,
    team: "enemy",
    className: "Commander",
    portraitKey: "mercenaryPortrait",
    spriteSet: "mercenary_male",
    facing: "down",
    x: 3,
    y: 1,
    move: 4,
    hp: 28,
    maxHp: 28,
    str: 8,
    mag: 1,
    def: 6,
    res: 4,
    spd: 6,
    luck: 4,
    sigilPoints: 3,
    maxSigilPoints: 3,
    weapons: [{ name: "Command Saber", baseDamage: 4, range: 1, damageType: "physical", stat: "str", hitRate: 95 }],
    acted: false,
    color: 0xf87171,
    boss: true,
  },
  {
    id: "elspeth",
    name: "Elspeth",
    title: "Guildlite Commander",
    level: 7,
    team: "enemy",
    className: "Commander",
    portraitKey: "mercenaryFemalePortrait",
    spriteSet: "mercenary_female",
    facing: "down",
    x: 6,
    y: 1,
    move: 4,
    hp: 24,
    maxHp: 24,
    str: 4,
    mag: 7,
    def: 4,
    res: 6,
    spd: 8,
    luck: 5,
    sigilPoints: 3,
    maxSigilPoints: 3,
    weapons: [{ name: "Glass Sigil", baseDamage: 4, minRange: 1, maxRange: 2, damageType: "magical", stat: "mag", hitRate: 95 }],
    acted: false,
    color: 0xfb7185,
    boss: true,
  },
  {
    id: "guildlite_guard_1",
    name: "Guildlite Guard",
    title: "Sword Detail",
    level: 5,
    team: "enemy",
    className: "Guard",
    portraitKey: "mercenaryPortrait",
    spriteSet: "sword_thug",
    facing: "down",
    x: 2,
    y: 2,
    move: 4,
    hp: 18,
    maxHp: 18,
    str: 6,
    mag: 0,
    def: 4,
    res: 2,
    spd: 5,
    luck: 3,
    sigilPoints: 3,
    maxSigilPoints: 3,
    weapons: [{ name: "Short Sword", baseDamage: 3, range: 1, damageType: "physical", stat: "str", hitRate: 95 }],
    acted: false,
    color: 0xfca5a5,
  },
  {
    id: "guildlite_guard_2",
    name: "Guildlite Guard",
    title: "Axe Detail",
    level: 5,
    team: "enemy",
    className: "Guard",
    portraitKey: "mercenaryFemalePortrait",
    spriteSet: "axe_thug",
    facing: "down",
    x: 7,
    y: 2,
    move: 4,
    hp: 20,
    maxHp: 20,
    str: 7,
    mag: 0,
    def: 4,
    res: 2,
    spd: 4,
    luck: 2,
    sigilPoints: 3,
    maxSigilPoints: 3,
    weapons: [{ name: "Hand Axe", baseDamage: 4, range: 1, damageType: "physical", stat: "str", hitRate: 90 }],
    acted: false,
    color: 0xfca5a5,
  },
];
