import { CHAPTER_ONE_UNITS } from "./chapter1.js";
import { CHAPTER_TWO_ALLY_UNITS } from "./chapter2.js";

export const CHAPTER_THREE_TITLE = { chapter: "Chapter 3", subtitle: "Tipen Whippet" };

export const CHAPTER_THREE_OPENING = [
  {
    type: "title",
    chapter: CHAPTER_THREE_TITLE.chapter,
    subtitle: CHAPTER_THREE_TITLE.subtitle,
    tag: "",
  },
  {
    type: "scene",
    sceneName: "Tipen Whippet Entrance",
    background: "chapter3TipenWhippetEntranceScene",
    lines: [
      { speaker: "Leon", portrait: "leonPortrait", text: "So this is civilisation?" },
      { speaker: "Kane", portrait: "kanePortrait", text: "Technically." },
      { speaker: "Leon", portrait: "leonPortrait", text: "That was not a ringing endorsement." },
      { speaker: "Kane", portrait: "kanePortrait", text: "It has a road, a shop, and three people who own opinions about lawn fertilizer. That is civilisation." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "It is Tipen Whippet." },
      { speaker: "Leon", portrait: "leonPortrait", text: "That sounds made up." },
      { speaker: "Kane", portrait: "kanePortrait", text: "Most places sound made up until you've been there." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Tipen Whippet sounds like a dog that went to private school." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "It is a town, Leon." },
      { speaker: "Leon", portrait: "leonPortrait", text: "I am not saying it is not. I am saying it sounds like it has a crest." },
      { speaker: "Kane", portrait: "kanePortrait", text: "It does." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Of course it does." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "A dog mauling a turnip." },
      { speaker: "Narration", portrait: null, text: "She strides off." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Wait! I can't tell if you're serious." },
    ],
  },
  {
    type: "scene",
    sceneName: "Tipen Whippet Main Road",
    background: "chapter3TipenWhippetMainRoadScene",
    lines: [
      { speaker: "Mara", portrait: "maraPortrait", text: "Isabella Roche, as I live and breathe." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Mara." },
      { speaker: "Mara", portrait: "maraPortrait", text: "Do not 'Mara' me like you were not going to sneak past." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "I was not sneaking." },
      { speaker: "Kane", portrait: "kanePortrait", text: "She was absolutely sneaking." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "I was walking with intent." },
      { speaker: "Mara", portrait: "maraPortrait", text: "And who is this?" },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Leon. Edwin's brother." },
      { speaker: "Mara", portrait: "maraPortrait", text: "Oh." },
      { speaker: "Leon", portrait: "leonPortrait", text: "That was a very loaded 'oh.'" },
      { speaker: "Mara", portrait: "maraPortrait", text: "Around here, love, most 'ohs' are loaded." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Your dress is beautiful." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Don't change the subject. Why is my brother problematic?" },
      { speaker: "Mara", portrait: "maraPortrait", text: "This old thing?" },
      { speaker: "Leon", portrait: "leonPortrait", text: "I know you can hear me." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "No. Do not do that. You know exactly what you are doing in that dress." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Fine. I give up." },
      { speaker: "Mara", portrait: "maraPortrait", text: "I bought it in a charity shop in Rye." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Then I must go to Rye sometime." },
      { speaker: "Leon", portrait: "leonPortrait", text: "I am sorry, is Izzy being charming?" },
      { speaker: "Kane", portrait: "kanePortrait", text: "Do not draw attention to it." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "I can be charming." },
      { speaker: "Kane", portrait: "kanePortrait", text: "Can you?" },
      { speaker: "Mara", portrait: "maraPortrait", text: "She has always been charming." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Thank you, Mara." },
      { speaker: "Mara", portrait: "maraPortrait", text: "You lot here for supplies?" },
      { speaker: "Kane", portrait: "kanePortrait", text: "Takeaway." },
      { speaker: "Mara", portrait: "maraPortrait", text: "Ah. Serious business. I'll let you get on." },
    ],
  },
  {
    type: "scene",
    sceneName: "Outside the Chinese Takeaway",
    background: "chapter3TakeawayExteriorScene",
    lines: [
      { speaker: "Leon", portrait: "leonPortrait", text: "This is the famous takeaway?" },
      { speaker: "Kane", portrait: "kanePortrait", text: "No one said famous." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Locally respected." },
      { speaker: "Leon", portrait: "leonPortrait", text: "That is what people say about haunted bridges." },
      { speaker: "Kane", portrait: "kanePortrait", text: "It is good food." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Do not. Kane once called a plate of burnt onion rings 'a culinary masterpiece.'" },
      { speaker: "Kane", portrait: "kanePortrait", text: "And it was." },
    ],
  },
  {
    type: "scene",
    sceneName: "Inside the Takeaway",
    background: "chapter3TakeawayInteriorScene",
    lines: [
      { speaker: "Gus", portrait: "gusPortrait", text: "Evening. Usual?" },
      { speaker: "Kane", portrait: "kanePortrait", text: "Usual, cheers Gus." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Add tofu." },
      { speaker: "Kane", portrait: "kanePortrait", text: "Why?" },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Because Grimmy likes it." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Grimmy likes tofu?" },
      { speaker: "Kane", portrait: "kanePortrait", text: "Grimmy likes anything he can describe as 'a texture adventure.'" },
      { speaker: "Leon", portrait: "leonPortrait", text: "Do you ever think prawns are the goblins of the sea?" },
      { speaker: "Kane", portrait: "kanePortrait", text: "No." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Absolutely not." },
      { speaker: "Leon", portrait: "leonPortrait", text: "That was too quick." },
      { speaker: "Kane", portrait: "kanePortrait", text: "It deserved speed." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Small. Suspicious. Too many legs. Feels like they know riddles." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Prawns do not know riddles." },
      { speaker: "Leon", portrait: "leonPortrait", text: "You do not know that." },
      { speaker: "Kane", portrait: "kanePortrait", text: "I know enough." },
      { speaker: "Leon", portrait: "leonPortrait", text: "If a prawn stopped me at a bridge, I would hear it out." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Why is there a bridge in the sea?" },
      { speaker: "Leon", portrait: "leonPortrait", text: "It is metaphorical." },
      { speaker: "Kane", portrait: "kanePortrait", text: "It is not." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Fine. A pier." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "That did not help." },
      { speaker: "Leon", portrait: "leonPortrait", text: "A prawn at the end of a pier asks you one question-" },
      { speaker: "Kane", portrait: "kanePortrait", text: "I am already walking away." },
      { speaker: "Leon", portrait: "leonPortrait", text: "-and if you get it wrong, you become a crab." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Why a crab?" },
      { speaker: "Leon", portrait: "leonPortrait", text: "Because crabs look like they failed a test." },
      { speaker: "Kane", portrait: "kanePortrait", text: "That might be the worst sentence I have heard today." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Today is still young." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "It is evening." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Then I have achieved something." },
      { speaker: "Kane", portrait: "kanePortrait", text: "You have achieved concern." },
      { speaker: "Leon", portrait: "leonPortrait", text: "I will take it." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Do not." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Do you think crabs know they are walking sideways, or is everyone else sideways to them?" },
      { speaker: "Kane", portrait: "kanePortrait", text: "No more animals." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Shellfish are not animals?" },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "They are." },
      { speaker: "Leon", portrait: "leonPortrait", text: "Then I withdraw the questi-" },
      { speaker: "SFX", portrait: null, text: "A woman screams outside." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Mara." },
      { speaker: "Kane", portrait: "kanePortrait", text: "Move." },
    ],
  },
  {
    type: "scene",
    sceneName: "Mara Threatened",
    background: "chapter3MaraThreatenedScene",
    lines: [
      { type: "fullScreenScene", scene: "chapter3MaraThreatenedScene", speaker: "Mercenary", text: "Where are the Bards?" },
      { speaker: "Mara", portrait: "maraPortrait", text: "I don't know who you mean." },
      { speaker: "Mercenary", portrait: "mercenaryPortrait", text: "Wrong answer." },
      { speaker: "Mara", portrait: "maraPortrait", text: "I do not know!" },
      { speaker: "Mercenary", portrait: "mercenaryPortrait", text: "They come here. People have seen them." },
      { speaker: "Mara", portrait: "maraPortrait", text: "People see all sorts." },
      { speaker: "Mercenary", portrait: "mercenaryPortrait", text: "Not helpful." },
      { speaker: "Mara", portrait: "maraPortrait", text: "I was not trying to be." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Take your hand off her." },
      { speaker: "Mercenary", portrait: "mercenaryPortrait", text: "And there they are." },
      { type: "fullScreenScene", scene: "chapter3IzzyWindAttackScene", speaker: "SFX", text: "WHOOMPH! Izzy blasts the thug back with a burst of wind." },
      { type: "fullScreenScene", scene: "chapter3IzzyWindAttackScene", speaker: "Leon", text: "I'm a FAN of how you work..." },
      { type: "fullScreenScene", scene: "chapter3IzzyWindAttackScene", speaker: "Kane", text: "No." },
      { type: "fullScreenScene", scene: "chapter3IzzyWindAttackScene", speaker: "Leon", text: "But-" },
      { type: "fullScreenScene", scene: "chapter3IzzyWindAttackScene", speaker: "Izzy", text: "No." },
    ],
  },
  {
    type: "scene",
    sceneName: "Mara Afterward",
    background: "chapter3MaraAfterwardScene",
    lines: [
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Mara. Look at me. Are you hurt?" },
      { speaker: "Mara", portrait: "maraPortrait", text: "No. I am alright." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Are you sure?" },
      { speaker: "Mara", portrait: "maraPortrait", text: "I am sure." },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Good." },
      { speaker: "Mara", portrait: "maraPortrait", text: "Izzy what did yo-" },
      { speaker: "Izzy", portrait: "izzyPortrait", text: "Later. Get inside and safe." },
    ],
  },
];

export const CHAPTER_THREE_POST_BATTLE_SCENE = [
  {
    type: "sceneDialogue",
    sceneName: "Tipen Whippet Aftermath",
    scene: "chapter3MaraAfterwardScene",
    speaker: "Leon",
    portrait: "leonPortrait",
    text: "Well. Nothing says victory like a half-burned street, a takeaway gone cold, and several new pals who definitely need a lie down.",
  },
  {
    type: "sceneDialogue",
    sceneName: "Tipen Whippet Aftermath",
    scene: "chapter3MaraAfterwardScene",
    speaker: "Kane",
    portrait: "kanePortrait",
    text: "That is your victory speech?",
  },
  {
    type: "sceneDialogue",
    sceneName: "Tipen Whippet Aftermath",
    scene: "chapter3MaraAfterwardScene",
    speaker: "Leon",
    portrait: "leonPortrait",
    text: "I was going to say we take all these new pals back to the farm and introduce them to Edwin.",
  },
  {
    type: "overlapDialogue",
    requiresRecruitedUnit: "ambrose",
    sceneName: "Tipen Whippet Aftermath",
    scene: "chapter3MaraAfterwardScene",
    speaker: "Ambrose",
    portrait: "ambrosePortrait",
    overlapPortrait: "leonPortrait",
    text: "Edwin Bligh?",
  },
  {
    type: "sceneDialogue",
    sceneName: "Tipen Whippet Aftermath",
    scene: "chapter3MaraAfterwardScene",
    speaker: "Leon",
    portrait: "leonPortrait",
    text: "Why does everyone say my brother's name like they just found it written on a cursed teapot?",
  },
  {
    type: "sceneNarration",
    sceneName: "Tipen Whippet Aftermath",
    scene: "chapter3MaraAfterwardScene",
    speaker: "Narration",
    portrait: null,
    text: "The town is alive, but the trail goes cold. Whatever the mercenaries came from, the Bards have missed the clue that would have pointed them there.",
  },
  {
    type: "sceneDialogue",
    sceneName: "Tipen Whippet Aftermath",
    scene: "chapter3MaraAfterwardScene",
    speaker: "Izzy",
    portrait: "izzyPortrait",
    text: "Then we move before more of them arrive.",
  },
  { type: "savePrompt", title: "Chapter 3 Complete", text: "Save game?" },
];

export const CHAPTER_THREE_SURVIVAL_TURNS = 10;

export const CHAPTER_THREE_TOWNSFOLK_IDS = [
  "townsperson_1",
  "townsperson_2",
  "townsperson_3",
  "townsperson_4",
  "townsperson_5",
];

export const CHAPTER_THREE_BATTLE_START_DIALOGUE = [
  {
    speaker: "Mercenary",
    portrait: "mercenaryPortrait",
    text: "Go for the townsfolk. The Bards'll have to come running.",
  },
  {
    speaker: "Ambrose",
    portrait: "ambrosePortrait",
    text: "Sorry about this lot. No manners, no shame, and Guildlites clearly hired cheap.",
  },
  {
    speaker: "Mercenary",
    portrait: "mercenaryFemalePortrait",
    text: "Who's that in the trees? Doesn't look like one of ours.",
  },
  {
    speaker: "Mercenary",
    portrait: "mercenaryPortrait",
    text: "That's the Black Phoenix. New boss's right hand. Best not gawp.",
  },
  {
    speaker: "Ash",
    portrait: "ashPortrait",
    text: "Oi. Picking on civilians now? That's not ambition, that's just pathetic.",
  },
];

export const CHAPTER_THREE_REWARDS = [
  {
    threshold: 1,
    type: "item",
    item: {
      id: "greggsSausageRoll",
      name: "Gregg's Sausage Roll",
      heal: 10,
      uses: 1,
      targetType: "selfOrAdjacentAlly",
      description: "Restore 10 HP to the user or an adjacent ally.",
    },
  },
  {
    threshold: 2,
    type: "weapon",
    weapon: {
      id: "mercenaryHammer",
      name: "Mercenary Hammer",
      baseDamage: 5,
      range: 1,
      damageType: "physical",
      stat: "str",
      hitRate: 95,
      defPierce: 5,
    },
  },
  {
    threshold: 3,
    type: "item",
    item: {
      id: "skillTome",
      name: "Skill Tome",
      uses: 1,
      targetType: "self",
      learnSkill: true,
      description: "Unlocks a skill based on the unit who reads it.",
    },
  },
  {
    threshold: 4,
    type: "weapon",
    weapon: {
      id: "esperanda",
      name: "Esperanda",
      baseDamage: 9,
      range: 1,
      damageType: "physical",
      stat: "str",
      hitRate: 100,
      speedBonus: 3,
      defPierce: 3,
    },
  },
  {
    threshold: 5,
    type: "item",
    item: {
      id: "townsBlessing",
      name: "Town's Blessing",
      uses: 1,
      targetType: "self",
      permanentStatBoost: 3,
      description: "Permanently adds +3 to every stat.",
    },
  },
];

export const CHAPTER_THREE_TOME_SKILLS = {
  edwin: { id: "frostguard", name: "Frostguard", cost: 2, type: "adjacentSquare", targetTeam: "enemy", damageFormula: "mag", animationState: "magic" },
  leon: { id: "haymaker", name: "Haymaker", cost: 1, type: "meleeSingle", targetTeam: "enemy", damageFormula: "strPlusSpd", animationState: "attack" },
  izzy: { id: "galeSweep", name: "Gale Sweep", cost: 2, type: "forwardRectangle", width: 3, depth: 2, targetTeam: "enemy", damageFormula: "strPlusSpd", animationState: "attack" },
  heath: { id: "undertow", name: "Undertow", cost: 2, type: "rangedSingle", range: 2, targetTeam: "enemy", damageFormula: "mag", animationState: "magic" },
  grimmy: { id: "boneCage", name: "Bone Cage", cost: 2, type: "adjacentSquare", targetTeam: "enemy", damageFormula: "mag", animationState: "magic" },
  kane: { id: "flashpoint", name: "Flashpoint", cost: 2, type: "adjacentSquare", targetTeam: "enemy", damageFormula: "strPlusMag", animationState: "attack" },
  shade: { id: "shadowstep", name: "Shadowstep", cost: 1, type: "selfBuff", damageFormula: "none", animationState: "move" },
  ambrose: { id: "sanctuary", name: "Sanctuary", cost: 2, type: "adjacentSquare", targetTeam: "ally", damageFormula: "resHeal", animationState: "magic" },
  fallback: { id: "battleFocus", name: "Battle Focus", cost: 1, type: "selfBuff", damageFormula: "none", animationState: "attack" },
};

export const MILO_RECRUITMENT_COTTAGE_KEY = "2,4";

export const MILO_SIGILS = {
  rabbit: {
    id: "rabbit",
    name: "Rabbit",
    stat: "spd",
    skill: { id: "rescueSprint", name: "Rescue Sprint", cost: 1, type: "rescueSprint", damageFormula: "none", animationState: "move" },
  },
  fox: {
    id: "fox",
    name: "Fox",
    stat: "mag",
    skill: { id: "decoyBoy", name: "Decoy Boy", cost: 1, type: "miloDecoy", damageFormula: "none", animationState: "magic" },
  },
  turtle: {
    id: "turtle",
    name: "Turtle",
    stat: "def",
    skill: { id: "slowRebuke", name: "Slow Rebuke", cost: 1, type: "slowRebuke", damageFormula: "none", animationState: "attack" },
  },
};

export const CHAPTER_THREE_MAP = [
  ["forest", "forest", "forest", "church", "forest", "forest", "forest", "forest"],
  ["forest", "forest", "forest", "forest", "forest", "forest", "forest", "forest"],
  ["pavement", "pavement", "pavement", "pavement", "pavement", "pavement", "pavement", "pavement"],
  ["road", "road", "road", "road", "road", "road", "road", "road"],
  ["cottage", "grass", "cottage", "grass", "chinese", "grass", "cottage", "grass"],
  ["pavement", "pavement", "pavement", "pavement", "pavement", "pavement", "pavement", "pavement"],
  ["road", "road", "road", "road", "road", "road", "road", "road"],
  ["pavement", "pavement", "pavement", "pavement", "pavement", "pavement", "pavement", "pavement"],
];

export const CHAPTER_THREE_COTTAGE_VISITS = {
  "0,4": {
    id: "westCottage",
    speaker: "Townsperson",
    portrait: "maraPortrait",
    text: "Here, love. Take this sausage roll. Gregg swears by them, and right now I'll take any miracle going.",
    item: {
      id: "greggsSausageRoll",
      name: "Gregg's Sausage Roll",
      heal: 10,
      uses: 1,
      targetType: "selfOrAdjacentAlly",
      description: "Restore 10 HP to the user or an adjacent ally.",
    },
  },
  "2,4": {
    id: "middleCottage",
    speaker: "Milo",
    portrait: "miloPortrait",
    text: "Crap, they found me! Oh wait, you're not one of them? Help me get out of here... please?",
    recruitMilo: true,
  },
  "6,4": {
    id: "eastCottage",
    speaker: "Townsperson",
    portrait: "maraPortrait",
    text: "Found this tucked over the door. Rabbit's Foot Tonic. Supposed to make your luck turn sharpish.",
    item: {
      id: "rabbitsFootTonic",
      name: "The Rabbit's Foot Tonic",
      uses: 1,
      targetType: "self",
      permanentLuckBoost: 3,
      description: "Permanently adds +3 Luck.",
    },
  },
};

function cloneUnit(unit, placement) {
  return {
    ...unit,
    ...placement,
    acted: false,
    spriteState: "idle",
    weapons: (unit.weapons || []).map((weapon) => ({ ...weapon })),
    skills: (unit.skills || []).map((skill) => ({ ...skill })),
    items: (unit.items || []).map((item) => ({ ...item })),
  };
}

const leon = CHAPTER_ONE_UNITS.find((unit) => unit.id === "leon");
const izzy = CHAPTER_TWO_ALLY_UNITS.find((unit) => unit.id === "izzy");
const kane = CHAPTER_TWO_ALLY_UNITS.find((unit) => unit.id === "kane");

export function createMiloUnit(placement = {}) {
  return {
    id: "milo",
    name: "Milo",
    title: "Latent",
    team: "player",
    className: "Latent",
    level: 1,
    xp: 0,
    xpRate: 1,
    latent: true,
    recruitedThisChapter: true,
    recruitmentStartLevel: 1,
    permanentRecruit: false,
    portraitKey: "miloPortrait",
    spriteSet: "milo",
    facing: "down",
    move: 5,
    hp: 14,
    maxHp: 14,
    str: 1,
    mag: 1,
    def: 1,
    res: 1,
    spd: 3,
    luck: 8,
    sigilPoints: 3,
    maxSigilPoints: 3,
    weapons: [{ id: "panicSwing", name: "Panic Swing", baseDamage: 1, range: 1, damageType: "physical", stat: "str", hitRate: 95 }],
    skills: [],
    items: [],
    acted: false,
    color: 0x22d3ee,
    ...placement,
  };
}

function createMercenary(id, placement, gender) {
  const isMale = gender === "male";
  return {
    id,
    name: "Mercenary",
    title: isMale ? "Guildlite Hammer" : "Guildlite Spear",
    team: "enemy",
    className: "Mercenary",
    level: 5,
    xp: 0,
    portraitKey: isMale ? "mercenaryPortrait" : "mercenaryFemalePortrait",
    spriteSet: isMale ? "mercenary_male" : "mercenary_female",
    facing: "down",
    move: 4,
    hp: isMale ? 14 : 12,
    maxHp: isMale ? 14 : 12,
    str: isMale ? 5 : 4,
    mag: 0,
    def: isMale ? 2 : 1,
    res: 1,
    spd: isMale ? 3 : 5,
    luck: 3,
    weapons: [isMale
      ? { name: "Mercenary Hammer", baseDamage: 5, range: 1, damageType: "physical", stat: "str", hitRate: 95, defPierce: 5 }
      : { name: "Mercenary Spear", baseDamage: 3, range: 1, damageType: "physical", stat: "str", hitRate: 95, lineThroughTarget: 2 }],
    skills: [],
    acted: false,
    color: isMale ? 0xf97316 : 0xf87171,
    ...placement,
  };
}

function createTownsperson(id, placement, spriteSet, portraitKey) {
  return {
    id,
    name: "Townsperson",
    title: "Civilian",
    team: "civilian",
    className: "Townsperson",
    portraitKey,
    spriteSet,
    facing: "down",
    move: 0,
    hp: 12,
    maxHp: 12,
    str: 0,
    mag: 0,
    def: 1,
    res: 1,
    spd: 0,
    luck: 0,
    weapons: [],
    skills: [],
    acted: false,
    color: 0xfacc15,
    ...placement,
  };
}

function createAsh(placement) {
  return {
    id: "ash",
    name: "Ash",
    title: "Black Phoenix",
    team: "enemy",
    className: "Flame Sigilist",
    level: 7,
    xp: 0,
    portraitKey: "ashPortrait",
    spriteSet: "ash",
    facing: "down",
    move: 4,
    hp: 30,
    maxHp: 30,
    str: 1,
    mag: 9,
    def: 1,
    res: 8,
    spd: 2,
    luck: 6,
    sigilPoints: 3,
    maxSigilPoints: 3,
    weapons: [{ id: "ashenFlameSigil", name: "Ashen Flame Sigil", baseDamage: 4, range: 1, damageType: "magical", stat: "mag", hitRate: 95 }],
    skills: [{
      id: "phoenixReckoning",
      name: "Phoenix Reckoning",
      cost: 1,
      type: "cardinalLine",
      range: 3,
      targetTeam: "enemy",
      damageFormula: "ashMissingHpMag",
      animationState: "attack",
      hitEffectKey: "phoenixReckoningHitEffect",
    }],
    acted: false,
    color: 0xdc2626,
    stationary: true,
    adjacentOnlyEnemy: true,
    ...placement,
  };
}

export const CHAPTER_THREE_UNITS = [
  cloneUnit(leon, { x: 0, y: 7, facing: "up" }),
  cloneUnit(izzy, { x: 1, y: 7, facing: "up" }),
  cloneUnit(kane, { x: 0, y: 6, facing: "up" }),
  {
    id: "ambrose",
    name: "Ambrose",
    title: "Churchwarden",
    team: "enemy",
    className: "Sentinel",
    level: 5,
    xp: 0,
    portraitKey: "ambrosePortrait",
    spriteSet: "ambrose",
    recruitmentId: "ambrose",
    facing: "down",
    x: 3,
    y: 0,
    move: 5,
    hp: 28,
    maxHp: 28,
    str: 8,
    mag: 0,
    def: 7,
    res: 5,
    spd: 3,
    luck: 5,
    weapons: [{ name: "Church Blade", baseDamage: 5, range: 1, damageType: "physical", stat: "str", hitRate: 95 }],
    skills: [],
    acted: false,
    color: 0xf59e0b,
    boss: true,
    stationary: true,
  },
  createMercenary("chapter3_mercenary_male_1", { x: 0, y: 0 }, "male"),
  createMercenary("chapter3_mercenary_male_2", { x: 1, y: 0 }, "male"),
  createMercenary("chapter3_mercenary_male_3", { x: 5, y: 0 }, "male"),
  createMercenary("chapter3_mercenary_male_4", { x: 7, y: 0 }, "male"),
  createMercenary("chapter3_mercenary_female_1", { x: 0, y: 1 }, "female"),
  createMercenary("chapter3_mercenary_female_2", { x: 2, y: 1 }, "female"),
  createAsh({ x: 3, y: 1 }),
  createMercenary("chapter3_mercenary_female_3", { x: 4, y: 1 }, "female"),
  createMercenary("chapter3_mercenary_female_4", { x: 6, y: 1 }, "female"),
  createTownsperson("townsperson_1", { x: 2, y: 6 }, "civ_man_1", "gusPortrait"),
  createTownsperson("townsperson_2", { x: 4, y: 6 }, "civ_man_2", "civMan2Portrait"),
  createTownsperson("townsperson_3", { x: 6, y: 6 }, "civ_woman_1", "civWoman1Portrait"),
  createTownsperson("townsperson_4", { x: 3, y: 5 }, "civ_woman_2", "civWoman2Portrait"),
  createTownsperson("townsperson_5", { x: 5, y: 5 }, "civ_woman_3", "maraPortrait"),
].filter(Boolean);
